Optimize Dockerfile
Rainist/akka-http.g8 pull request #2
Opened 2019-01-09 02:30 UTC by kanziw

Dockerfile 에 multi stage 개념을 도입하였습니다.
또한 컨테이너 내에서 JVM 메모리 관리에 도움을 주는 옵션을 추가하였습니다.

2019-01-09 02:33 UTC, devholic requested changes

2019-01-09 02:33 UTC, devholic commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-slim-stretch AS build
대부분의 경우에는 `alpine`을 사용하고 있기 때문에 `slim-stretch`보다는 `alpine`을 사용하는게 좋을 것 같습니다 🙏

2019-01-09 02:33 UTC, devholic commented on src/main/g8/Dockerfile
> +ADD ./src /app/src
이 커맨드도 `COPY`로 대체하면 좋을 것 같아요 🙏

2019-01-09 02:33 UTC, devholic commented on src/main/g8/Dockerfile
> +FROM openjdk:8u181-jre-slim-stretch
맨 위 코멘트와 마찬가지입니당~

2019-01-09 02:39 UTC, sunghyunzz commented on src/main/g8/docker-compose.yml
>      command: sbt "~ ;reStart ; run"
기존 Dockerfile이 `RUN sbt compile` 에서 끝나고 `.jar` 생성까지 하지 않은 이유는 `docker-compose`를 이용하여 런타임 테스트/디버깅을 용이하게 하기 위함이었습니다. 이번 PR을 통해 `build`에서 `assembly` 까지 실행한다면 `command`가 이에 상응하도록 변경되거나, Dockerfile이 변경될 필요가 있을 것 같습니다.

2019-01-09 02:46 UTC, devholic commented on src/main/g8/docker-compose.yml
>      command: sbt "~ ;reStart ; run"
`compile` stage를 추가하면 좋을 것 같네용 :D

2019-01-09 04:01 UTC, kanziw commented on src/main/g8/docker-compose.yml
>      command: sbt "~ ;reStart ; run"
오.. 저도 같은 생각을 했었습니다! @devholic

2019-01-09 04:01 UTC, kanziw commented on src/main/g8/docker-compose.yml
>      command: sbt "~ ;reStart ; run"
https://github.com/Rainist/scala.g8/pull/2/commits/a6356308cecab897fdd6ec6b4a773021ec355506
작업한 내용 리뷰 부탁드립니다 @sunghyunzz @devholic

2019-01-09 04:04 UTC, devholic commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-alpine AS build
`packaging`이 좀 더 좋지 않을까유?

2019-01-09 05:18 UTC, kanziw commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-alpine AS build
# Pack

2019-02-11 00:37 UTC, sunghyunzz commented on src/main/g8/default.properties
> +scala_version_short=2.12
위의 `scala_version`과 내용이 사실 겹치는데, 저희가 필요한 format을 giter8에서 지원하질 않네요😭 아예 이걸 archive된 jar파일이 저장되는 directory name으로 바꿔서 리팩토링 해보면 어떨까요? `scala_version`과 `scala_version_short`를 사용자에게 둘 다 입력 받는다는 게 두 값의 불일치가 있을 수 있어 (잘못된 사용을 유도할 수 있는 것 같아) 찝찝하네요 😢

2019-02-12 06:46 UTC, kanziw commented on src/main/g8/default.properties
> +scala_version_short=2.12
참고 [링크](https://stackoverflow.com/questions/28521706/custom-outputpath-for-sbt-assembly)

build.sbt 에 `assemblyOutputPath` 를 아래처럼 추가하고
```scala
import Dependencies._

lazy val root = (project in file(".")).settings(
  ...
  assemblyJarName in assembly := "$name;format="normalize"$.jar",
  assemblyOutputPath := new File("/app/target/$name$")
)
```

Dockerfile 에서 `$scala_version_short$` 을 사용하는 부분을
```
COPY --from=build /app/target/$name$/app.jar /app/app.jar
```

요래 바꿔보는건 어떨까요? 아예 `$scala_version_short$` 을 빼구요~ @sunghyunzz 

(직접 해보진 않고 링크의 힘을 빌려 아이디어만 적어봤습니다...)

2019-02-12 06:50 UTC, kanziw commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-alpine AS build
compiler -> packer -> #Runtime 으로 빌드 스테이지 이름을 가져가는건 어떤가요?
https://docs.docker.com/develop/develop-images/multistage-build/ 에 보면 예제에도 builder 라는 이름을 사용하고 있어서 뒤에 `er` 붙이는게 어색하진 않을것 같아서요~ @devholic

2019-07-07 04:15 UTC, JungWinter commented
Any update?

2019-07-08 00:57 UTC, kanziw commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-alpine AS build
Hi~ @devholic ? How about my naming? :)

2019-07-08 04:50 UTC, kanziw commented on src/main/g8/default.properties
> +scala_version_short=2.12
https://github.com/Rainist/scala.g8/compare/a6356308cecab897fdd6ec6b4a773021ec355506..44043ea2498b5184f91129a5e00af932e25e11eb
요렇게 적용해보았고 제 로컬에선 jar 파일까지 잘 만들어지는 것 같습니다!

2019-07-09 00:45 UTC, ryuheechul commented on src/main/g8/Dockerfile
> +FROM rainist/sbt:$sbt_version$-alpine AS build
말씀하신 것 처럼 모두 `-er` 을 붙여주시면 더 좋을 것 같습니다.

2019-07-09 02:34 UTC, kanziw commented
@charlie-world 님께서 추가적으로 더 Optimize 해주셨습니다. 감사합니다.
제 로컬에서 테스트 했을 땐 현재 커밋 기준으로 정상 동작합니다. 리뷰 부탁드려요~

2019-07-09 02:44 UTC, winterjung requested changes
도커 컴포즈가 개발환경 목적으로 필요하단 의견이 있어 대신 코멘트합니당. @sunghyunzz

2019-07-09 05:55 UTC, kanziw commented
docker-compose 는 보통 다른 docker 이미지에 디펜던시가 있는 경우 주로 사용하는 것 같습니다.

모든 프로젝트에서 docker-compose 가 필요하진 않으니 template 으로 사용하는 레포인 만큼 docker-compose 없이 minimum 하게 가는것 도 좋지 않을까요? @sunghyunzz

2019-07-09 06:01 UTC, ryuheechul commented
존재하고 있던 도커컴포즈 파일이 어떤 이유로 지워져야 하는지에 대해서 저도 의문입니다.
위 개발환경 목적으로 필요하시다고 말씀하신 건 현재 그렇게 쓰고 계시다는 것 같아요.
혹시라도 클린업을 위한 클린업의 방향이라면 경계 되어야하지 않을까 생각합니다.

2019-07-09 06:06 UTC, charlie-world commented
저는 개인적으로 도커 컴포즈가 필요한 서비스 에서 작성 하면 되지 않을까 합니다.
필수로 도커 컴포스를 다 추가 해야 한다고 생각하진 않습니다.

2019-07-09 06:06 UTC, sunghyunzz commented
@kanziw 저의 관점은 template이기 때문에 어느 정도 공통적인 성격을 띄는 파일이라면 남겨두고 각 프로젝트에 알맞게 삭제하는 게 좋지 않을까?입니다. 다른 Docker image와의 의존성이 없더라도 로컬에 Scala, SBT 등을 설치하지 않고 도커 기반으로 개발 환경을 이용하는 경우가 많아 편리하기도 하고요 😅

2019-07-09 08:16 UTC, ryuheechul commented
(뜬금 코멘트)

> 존재하고 있던 도커컴포즈 파일이 어떤 이유로 지워져야 하는지에 대해서 저도 의문입니다.
> 위 개발환경 목적으로 필요하시다고 말씀하신 건 현재 그렇게 쓰고 계시다는 것 같아요.
> 혹시라도 클린업을 위한 클린업의 방향이라면 경계 되어야하지 않을까 생각합니다.

위 코멘트를 쓰고 나서 종종 왜인지 모르게 계속 생각나고 마음에 걸렸습니다.
그리고 다시 읽어보고 나서 제가 이 코멘트를 전달 받은 입장이라고 생각했을 때에도 별로 달갑지 않네요.
그 동안 읽는 사람에 대한 배려가 부족했거나 충분히 생각지 못하고서 (제가) 달았던 코멘트가 많았을 것 같은데 앞으로 의견의 내용자체만 집중하는 것이 아니라 좀 더 읽고 싶은 코멘트를 작성할 수 있도록 노력하겠습니다.

2019-07-09 08:47 UTC, kanziw commented
@sunghyunzz 아하.. 그 관점이었군요~ 이해 되었습니다.
로컬 개발환경 + IntelliJ 환경 이 빠르고 또 너무 편하다보니 당연하다고 생각했네요.ㅎㅎ
관련된 Makefile & docker-compose.yml 복구하고 이에 맞게 Dockerfile 멀티스테이징 설정도 이에 맞게 수정하는게 맞겠다는 생각이 듭니다.

나중에 혹~시 docker-compose 를 빼자는 컨선이 동기화 되면 그 때 빼는 것으로 하는건 어떨까요? @charlie-world

2019-07-09 08:48 UTC, charlie-world commented
✅

2019-07-12 02:16 UTC, winterjung approved these changes

2019-07-12 02:18 UTC, kanziw commented
@sunghyunzz 님~! docker-compose 관련 파일 다시 추가하여 커밋 하였습니다. 한번 봐주세요 🙏

2019-07-12 02:19 UTC, 0xd669 approved these changes
L.G.T.M 👍

2019-07-12 02:31 UTC, merged